name: AndroidBuild
on:
  pull_request:
    branches: [ clean-architecture ]
  push :
    branches: [ clean-architecture ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create blank google-services.json (for Firebase)
        run: cat /home/runner/work/Synflix/Synflix/app/google-services.json | base64

      - name: Generate google-services.json from secrets
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/Synflix/Synflix/app/google-services.json

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}

        run: |
          echo $ENCODED_STRING > keystore-b64.txt
          base64 -d keystore-b64.txt > $SIGNING_KEY_STORE_PATH

      - name: Build Unsigned APK Debug Paid Variant with Gradle
        run: ./gradlew assemblePaidDebug

      - name: Build Unsigned APK Debug Free Variant with Gradle
        run: ./gradlew assembleFreeDebug

      - name: Build Android Bundle (.aab) Release Free Variant
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew bundleFreeRelease

      - name: Build Android Bundle (.aab) Release Paid Variant
        env:
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: ./gradlew bundlePaidRelease

      - name: Upload .apk
        uses: actions/upload-artifact@v4.3.3
        with:
          name: synflix_apk
          path: app/build/outputs/apk/

      - name: Upload .aab
        uses: actions/upload-artifact@v4.3.3
        with:
          name: synflix_release_aab
          path: app/build/outputs/bundle/






